---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidymodels)
library(ggplot2)
library(randomForest)
library(gbm)
library(caret)
library(xgboost)
library(table1)
library(car)
```

```{r}
set.seed(123)
```

```{r}
data <- read.table("/Users/rango/documents/stt3781/project1/data.txt", header = TRUE, sep = "\t")
data
data$CARDIA <- factor(data$CARDIA)
```

```{r}
counts <- table(data$CARDIA)
print(counts)
```

```{r}
barplot(counts, main = "Class Frequency", xlab = "Class", ylab = "Frequency", col = "lightgreen")
```

```{r}
#set.seed(42)  # For reproducibility
split <- initial_split(data, prop = 0.8)
train_data <- training(split)
test_data <- testing(split)
```

```{r}
rf_model <- rand_forest(mtry = 3, trees = 500, min_n = 8) %>%
  set_mode("classification") %>%
  set_engine("randomForest")
```

```{r}
recipe <- recipe(CARDIA ~ ., data = test_data)
```

```{r}
workflow_rf <- workflow() %>%
  add_recipe(recipe) %>%
  add_model(rf_model)
```

```{r}
#cv_folds <- vfold_cv(train_data, v = 5)
```

```{r}
#rf_grid <- grid_regular(
#  mtry(range = c(2, 11)),
#  min_n(range = c(5, 20))
#)
```

```{r}
#rf_tune_results <- tune_grid(
#  workflow_rf,
#  resamples = cv_folds,
#  grid = rf_grid,
#  metrics = metric_set(yardstick::accuracy)
#)
```

```{r}
#rf_tune_results %>% autoplot()
```

```{r}
#best_params <- rf_tune_results %>% select_best(metric = "accuracy")
#final_rf <- finalize_workflow(workflow_rf, best_params)
```

```{r}
#final_rf_fit <- final_rf %>% fit(data = train_data)
```

```{r}
rf_fit <- fit(workflow_rf, data = train_data)
```

```{r}
rf_predictions <- predict(rf_fit, new_data = test_data)

rf_results <- bind_cols(test_data, rf_predictions)

rf_conf_mat <- conf_mat(rf_results, truth = CARDIA, estimate = .pred_class)
print(rf_conf_mat)
```

```{r}
rf_accuracy <- accuracy(rf_results, truth = CARDIA, estimate = .pred_class)
print(rf_accuracy)
```

```{r}
gb_model <- boost_tree(
  trees = 1000,
  mtry = 3,
  learn_rate = 0.01,
  tree_depth = 3
) %>%
  set_engine("xgboost") %>%
  set_mode("classification")
```

```{r}
workflow_gb <- workflow() %>%
  add_recipe(recipe) %>%
  add_model(gb_model)
```

```{r}
#gb_grid <- grid_regular(
#  trees(range = c(500, 1000)),      
#  tree_depth(range = c(1, 5)),    
#  learn_rate(range = c(0.01, 0.1)),  
#  mtry(range = c(3,11))
#)
```

```{r}
#gb_tune_results <- tune_grid(
#  workflow_gb,
#  resamples = cv_folds,
#  grid = gb_grid,
#  metrics = metric_set(yardstick::accuracy)
#)
```

```{r}
#gb_tune_results %>% autoplot()
```

```{r}
#gb_best_params <- gb_tune_results %>% select_best(metric = "accuracy")
#print(gb_best_params)
#final_gb <- finalize_workflow(workflow_gb, gb_best_params)
```

```{r}
#final_gb_fit <- final_gb %>% fit(data = train_data)
```

```{r}
gb_fit <- fit(workflow_gb, data = train_data)
```

```{r}
gb_predictions <- predict(gb_fit, new_data = test_data)

gb_results <- bind_cols(test_data, gb_predictions)

gb_conf_mat <- conf_mat(gb_results, truth = CARDIA, estimate = .pred_class)
print(gb_conf_mat)
```

```{r}
gb_accuracy <- accuracy(gb_results, truth = CARDIA, estimate = .pred_class)
print(gb_accuracy)
```

```{r}
logistic_model <- glm(formula = CARDIA ~ AGE + factor(SEXE) + PSYST + factor(PHYS) + NB_HT + factor(HIS_C) + factor(HISFAM_C) + factor(FUMEUR) + factor(DIAB) + IMC + SES, family = "binomial", data = data)
logistic_model
```

```{r}
log_odds <- predict(logistic_model, type = "link")
```

```{r}
ggplot(data, aes(x = AGE, y = log_odds)) +
  geom_point(color = "blue") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    title = "Log Odds vs Age",
    x = "Age",
    y = "Log Odds"
  ) +
  theme_minimal()
```

```{r}
ggplot(data, aes(x = PSYST, y = log_odds)) +
  geom_point(color = "blue") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    title = "Log Odds vs PSYST",
    x = "PSYST",
    y = "Log Odds"
  ) +
  theme_minimal()
```

```{r}
ggplot(data, aes(x = IMC, y = log_odds)) +
  geom_point(color = "blue") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    title = "Log Odds vs IMC",
    x = "IMC",
    y = "Log Odds"
  ) +
  theme_minimal()
```

```{r}
proportions_nb_ht <- data %>%
  group_by(NB_HT) %>%
  summarise(proportion = mean(CARDIA == 1))
```

```{r}
ggplot(proportions_nb_ht, aes(x = NB_HT, y = proportion, color = NB_HT)) +
  geom_point(size = 3, show.legend = FALSE) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(
    title = "Proportion of Cardiac Cases by NB_HT Modality",
    x = "NB_HT Modality",
    y = "Proportion of Cardiac Cases"
  ) +
  theme_minimal()
```

```{r}
proportions_imc <- data %>%
  group_by(IMC) %>%
  summarise(proportion = mean(CARDIA == 1))
```

```{r}
ggplot(proportions_imc, aes(x = IMC, y = proportion, color = IMC)) +
  geom_point(size = 3, show.legend = FALSE) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(
    title = "Proportion of Cardiac Cases by IMC Modality",
    x = "IMC Modality",
    y = "Proportion of Cardiac Cases"
  ) +
  theme_minimal()
```

```{r}
proportions_ses <- data %>%
  group_by(SES) %>%
  summarise(proportion = mean(CARDIA == 1))
```

```{r}
ggplot(proportions_ses, aes(x = SES, y = proportion, color = SES)) +
  geom_point(size = 3, show.legend = FALSE) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(
    title = "Proportion of Cardiac Cases by SES Modality",
    x = "SES Modality",
    y = "Proportion of Cardiac Cases"
  ) +
  theme_minimal()
```

```{r}
vif(logistic_model)
```

```{r}
dev_residuals <- residuals(logistic_model, type = "deviance")
predicted_probs <- predict(logistic_model, type = "response")
```

```{r}
dev_residuals_df <- data.frame(dev_residuals)
ggplot(dev_residuals_df, aes(sample = dev_residuals)) +
  stat_qq() +
  stat_qq_line(color = "red", size = 1.2) +
  ggtitle("Q-Q Plot of Deviance Residuals") +
  theme_minimal()
```

```{r}
logistic_model <- glm(formula = CARDIA ~ AGE + factor(SEXE) + factor(PHYS) + NB_HT + factor(HIS_C) + factor(HISFAM_C) + factor(FUMEUR) + factor(DIAB) + IMC + SES, family = "binomial", data = data)
logistic_model
```

```{r}
dev_residuals <- residuals(logistic_model, type = "deviance")
predicted_probs <- predict(logistic_model, type = "response")
```

```{r}
dev_residuals_df <- data.frame(dev_residuals)
ggplot(dev_residuals_df, aes(sample = dev_residuals)) +
  stat_qq() +
  stat_qq_line(color = "red", size = 1.2) +
  ggtitle("Q-Q Plot of Deviance Residuals") +
  theme_minimal()
```

```{r}
#plot_data <- data.frame(Predicted = log_odds, DevianceResiduals = dev_residuals)

# Plot with ggplot2
#ggplot(plot_data, aes(y = DevianceResiduals, x = log_odds)) +
#  geom_point(color = "steelblue", alpha = 0.6) +
#  labs(title = "Deviance Residuals vs Predicted Values",
#       x = "Predicted values",
#       y = "Deviance Residuals") +
#  theme_minimal()
```
